from config.kitti_model_config import kitti_model_config
from config.kitti_squeezeDet_config import kitti_squeezeDet_config
from config.kitti_squeezeDetPlus_config import kitti_squeezeDetPlus_config
from config.coco_config import coco_config
